# -*- coding: utf-8 -*-
"""
声明、定义
"""


FAIL = "FAIL"
SUCCESS = "SUCCESS"

#登录检查结果码
class LOGINCODE:
	"""
	"""
	CHECK_LOGIN_SUCCESS 			= 0		#成功
	CHECK_LOGIN_ARGS_ERROR 			= 1		#参数错误
	CHECK_LOGIN_SIGN_ERROR			= 2		#签名错误
	CHECK_LOGIN_PASSWD_ERROR		= 3		#密码错误
	CHECK_LOGIN_UNKNOW_ERROR		= 4		#系统错误
	CHECK_LOGIN_ACCOUNT_NOT_EXISTS 	= 5		#账号不存在或未激活


#充值结果码
class CHARGERESULTCODE:
	RESULT_TYPE_SUCCESS 				= 0 	#成功
	RESULT_TYPE_FAILD					= 1 	#失败
	RESULT_TYPE_ACCOUNT_NOT_EXIST		= 101 	#账号不存在
	RESULT_TYPE_INFO_INCOMPLETE			= 103 	#资料不齐全
	RESULT_TYPE_SIGN_ERROR				= 401 	#签名错误
	RESULT_TYPE_ORDER_IS_EXECUTED		= 200 	#订单已经成功执行
	RESULT_TYPE_ORDER_NOT_EXIST			= 201 	#不存在该订单

class CHARGERESULTINFO:
	RESULT_INFO_SUCCESS 			= "成功"
	RESULT_INFO_FAILD				= "失败"
	RESULT_INFO_ACCOUNT_NOT_EXIST	= "账号不存在"
	RESULT_INFO_INFO_INCOMPLETE		= "资料不齐全"
	RESULT_INFO_SIGN_ERROR			= "签名错误"
	RESULT_INFO_SIGN_TYPE_ERROR		= "签名类型不匹配"
	RESULT_INFO_ORDER_IS_EXECUTED	= "订单已经成功执行"
	RESULT_INFO_ORDER_NOT_EXIST		= "不存在该订单"
	RESULT_INFO_ORDER_ALREADY_EXIST	= "存在已订单"
	RESULT_INFO_VALID_TIME_OVER		= "有效时间已过"
	RESULT_INFO_AMOUNT_VALUE_ERROR	= "充值数量不正确"
	RESULT_INFO_NOTICE_SERVER_ERROR	= "充值成功，但是通知服务器失败"
	RESULT_INFO_GRADE_NOT_ENOUGH	= "没有访问权限"
	