# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-07-15 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GMAccountMgrLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updateTime', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('serverKey', models.CharField(default='', help_text='服务器key', max_length=128)),
                ('serverName', models.CharField(default='', help_text='服务器名字', max_length=128)),
                ('userID', models.CharField(db_index=True, default='', help_text='操作者用户账号', max_length=128)),
                ('userLevel', models.IntegerField(default=0, help_text='操作者用户等级')),
                ('actionType', models.IntegerField(default=0, help_text='操作类型')),
                ('targetAccount', models.CharField(default='', help_text='操作账号', max_length=128)),
                ('param1', models.CharField(default='', help_text='扩展参数1', max_length=128)),
                ('param2', models.CharField(default='', help_text='扩展参数2', max_length=128)),
                ('param3', models.CharField(default='', help_text='扩展参数3', max_length=128)),
            ],
            options={
                'db_table': 'gm_acc_mgr_log',
            },
        ),
        migrations.CreateModel(
            name='GMActivityMgrInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updateTime', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('serverKey', models.CharField(default='', help_text='服务器key', max_length=128)),
                ('serverName', models.CharField(default='', help_text='服务器名字', max_length=128)),
                ('userID', models.CharField(db_index=True, default='', help_text='操作者用户账号', max_length=128)),
                ('userLevel', models.IntegerField(default=0, help_text='操作者用户等级')),
                ('actionType', models.IntegerField(default=0, help_text='操作类型')),
                ('activityKey', models.CharField(default='', help_text='活动key', max_length=128)),
                ('activityName', models.CharField(default='', help_text='活动名字', max_length=128)),
                ('param1', models.CharField(default='', help_text='扩展参数1', max_length=128)),
            ],
            options={
                'db_table': 'gm_activity_log',
            },
        ),
        migrations.CreateModel(
            name='GMAwardRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('applicationTime', models.CharField(default='2020-07-15 15:03:24', max_length=128)),
                ('award_targetType', models.CharField(default='', max_length=1280)),
                ('award_title', models.CharField(default='', max_length=30)),
                ('award_reason', models.CharField(default='', max_length=128)),
                ('award_roleList', models.CharField(default='', max_length=1280)),
                ('award_itemList', models.CharField(default='', max_length=128)),
                ('applicant', models.CharField(default='', max_length=30)),
                ('sendState', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'gm_awardRecord',
            },
        ),
        migrations.CreateModel(
            name='GMItemMgrLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updateTime', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('serverKey', models.CharField(default='', help_text='服务器key', max_length=128)),
                ('serverName', models.CharField(default='', help_text='服务器名字', max_length=128)),
                ('userID', models.CharField(db_index=True, default='', help_text='操作者用户账号', max_length=128)),
                ('userLevel', models.IntegerField(default=0, help_text='操作者用户等级')),
                ('actionType', models.IntegerField(default=0, help_text='操作类型')),
                ('targetType', models.IntegerField(default=0, help_text='公告次数')),
                ('roleList', models.TextField(default='', help_text='玩家信息')),
                ('itemList', models.CharField(default='', help_text='物品信息', max_length=128)),
                ('title', models.CharField(default='', help_text='标题', max_length=128)),
                ('content', models.CharField(default='', help_text='内容', max_length=255)),
                ('param1', models.CharField(default='', help_text='扩展参数1', max_length=128)),
                ('param2', models.CharField(default='', help_text='扩展参数2', max_length=128)),
                ('param3', models.CharField(default='', help_text='扩展参数3', max_length=128)),
            ],
            options={
                'db_table': 'gm_item_mgr_log',
            },
        ),
        migrations.CreateModel(
            name='GMMailMgrLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updateTime', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('serverKey', models.CharField(default='', help_text='服务器key', max_length=128)),
                ('serverName', models.CharField(default='', help_text='服务器名字', max_length=128)),
                ('userID', models.CharField(db_index=True, default='', help_text='操作者用户账号', max_length=128)),
                ('userLevel', models.IntegerField(default=0, help_text='操作者用户等级')),
                ('actionType', models.IntegerField(default=0, help_text='操作类型')),
                ('targetType', models.IntegerField(default=0, help_text='公告次数')),
                ('roleList', models.TextField(default='', help_text='玩家信息')),
                ('itemList', models.CharField(default='', help_text='物品信息', max_length=128)),
                ('title', models.CharField(default='', help_text='标题', max_length=128)),
                ('content', models.CharField(default='', help_text='内容', max_length=255)),
                ('moneyAmount', models.IntegerField(default=0, help_text='公告间隔时间')),
            ],
            options={
                'db_table': 'gm_mail_mgr_log',
            },
        ),
        migrations.CreateModel(
            name='GMNoticeMgrLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updateTime', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('serverKey', models.CharField(default='', help_text='服务器key', max_length=128)),
                ('serverName', models.CharField(default='', help_text='服务器名字', max_length=128)),
                ('userID', models.CharField(db_index=True, default='', help_text='操作者用户账号', max_length=128)),
                ('userLevel', models.IntegerField(default=0, help_text='操作者用户等级')),
                ('actionType', models.IntegerField(default=0, help_text='操作类型')),
                ('noticeTimes', models.IntegerField(default=0, help_text='公告次数')),
                ('intervalTime', models.IntegerField(default=0, help_text='公告间隔时间')),
                ('title', models.CharField(default='', help_text='标题', max_length=128)),
                ('content', models.TextField(default='', help_text='内容')),
                ('param1', models.CharField(default='', help_text='扩展参数1', max_length=128)),
                ('param2', models.CharField(default='', help_text='扩展参数2', max_length=128)),
                ('param3', models.CharField(default='', help_text='扩展参数3', max_length=128)),
            ],
            options={
                'db_table': 'gm_notice_mgr_log',
            },
        ),
        migrations.CreateModel(
            name='GMRoleMgrLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updateTime', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('serverKey', models.CharField(default='', help_text='服务器key', max_length=128)),
                ('serverName', models.CharField(default='', help_text='服务器名字', max_length=128)),
                ('userID', models.CharField(db_index=True, default='', help_text='操作者用户账号', max_length=128)),
                ('userLevel', models.IntegerField(default=0, help_text='操作者用户等级')),
                ('actionType', models.IntegerField(default=0, help_text='操作类型')),
                ('targetRole', models.CharField(default='', help_text='操作角色', max_length=128)),
                ('param1', models.CharField(default='', help_text='扩展参数1', max_length=128)),
                ('param2', models.CharField(default='', help_text='扩展参数2', max_length=128)),
                ('param3', models.CharField(default='', help_text='扩展参数3', max_length=128)),
            ],
            options={
                'db_table': 'gm_role_mgr_log',
            },
        ),
        migrations.CreateModel(
            name='GMUserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updateTime', models.DateTimeField(auto_now_add=True, help_text='记录时间')),
                ('serverKey', models.CharField(default='', help_text='服务器key', max_length=128)),
                ('serverName', models.CharField(default='', help_text='服务器名字', max_length=128)),
                ('userID', models.CharField(db_index=True, default='', help_text='操作者用户账号', max_length=128)),
                ('userLevel', models.IntegerField(default=0, help_text='操作者用户等级')),
                ('actionType', models.IntegerField(default=0, help_text='操作类型')),
                ('targetUserID', models.CharField(default='', help_text='操作对象', max_length=128)),
                ('targetUserLevel', models.IntegerField(default=0, help_text='操作对象等级')),
                ('param1', models.CharField(default='', help_text='扩展参数1', max_length=128)),
                ('param2', models.CharField(default='', help_text='扩展参数2', max_length=128)),
                ('param3', models.CharField(default='', help_text='扩展参数3', max_length=128)),
            ],
            options={
                'db_table': 'gm_user_log',
            },
        ),
        migrations.CreateModel(
            name='GMUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(db_index=True, default='', help_text='用户账户ID', max_length=128)),
                ('userName', models.CharField(db_index=True, default='', help_text='用户名', max_length=128)),
                ('password', models.CharField(default='', help_text='密码', max_length=128)),
                ('level', models.IntegerField(default=3)),
            ],
            options={
                'db_table': 'gm_user',
            },
        ),
    ]
