# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-27 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmuser',
            name='auth_notice',
            field=models.IntegerField(default=0),
        ),
    ]
